baseurl = "http://tomashley.github.io/"
languageCode = "en-gb"
title = "tomashley"
theme = "slender"
MetaDataFormat = "toml"
paginate = 5
PaginatePath = "/"
canonifyurls = true


[author]
    name = "Tom Ashley"

[permalinks]

    # Permalink format for blog posts.
    # post = "/post/:title/"
    post = "/:year/:month/:day/:filename/"

[params]

    intro = true
    # Change the color scheme of Slender.
    # See above for preview and list of color schemes.
    colorscheme = "green"

  
    # Tagline; HTML accepted here. Keep it concise.
    # tagline = "Building blocks, not pouring concrete<br /><img src=/images/site-logo.png width=\"80\" height=\"80\""
    tagline = "Building blocks, not pouring concrete"

    # Footer; Markdown accepted here.
    footer = "Copyright 2013 - 2016 &copy; Tom Ashley"

    # Description and keywords for <meta> tags.
    # Remember to set this for your main page.
    # This will be overridden by whatever is set by the page or post,
    # defined by `description` and `keywords` variables in the front matter
    # of the markdown file.
    description = "Technically, a blog"
    keywords = "default,page,keywords"

    # Social links, must be full URLs (e.g. https://github.com/CrimsonRay/).
    # Remove, comment, or leave blank any field to leave them out.
    email = "mailto:tom.ashley+githubio@gmail.com"
    github = "https://github.com/tomashley"
    # bitbucket = "https://bitbucket.org/tomashley/"
    twitter = "https://twitter.com/vimclaw"
    # stackoverflow = "url-to-your-stackoverflow"
    # linkedin = "url-to-your-linkedin"
    # facebook = "url-to-your-facebook"

    # Google Analytics
    # Remove, comment, or leave it blank if you don't have one.
    ganalytics = "UA-42095920-2"

[menu]

    # Menu for the nav bar.
    # There must always be one item present (e.g. home).
    [[menu.main]]
    identifier = "home"
    name       = "home"
    url        = "/"
    weight     = 0

    [[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "/about/"
    weight     = 1
